### ISSUE TITLE
Uncaught Error: Cannot find module '/Applications/Atom.app/Contents/Resources/app/node_modules/git-diff'

### ISSUE THREAD

**Issue by matijaabicic** [atom-minimap/minimap-git-diff#12]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: [minimap-git-diff](https://github.com/atom-minimap/minimap-git-diff) package, v3.0.4

### Stack Trace

Uncaught Error: Cannot find module '/Applications/Atom.app/Contents/Resources/app/node_modules/git-diff'

```
At module.js:346

Error: Cannot find module '/Applications/Atom.app/Contents/Resources/app/node_modules/git-diff'
  at Module._resolveFilename (module.js:344:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:380:52)
  at Function.Module._load (module.js:286:25)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at new MinimapGitDiffBinding (/Users/matijaabicic/.atom/packages/minimap-git-diff/lib/minimap-git-diff-binding.coffee:13:16)
  at /Users/matijaabicic/.atom/packages/minimap-git-diff/lib/minimap-git-diff.coffee:63:21
  at Minimap.module.exports.ViewManagement.eachMinimapView (/Users/matijaabicic/.atom/packages/minimap/lib/mixins/view-management.coffee:50:5)
  at MinimapGitDiff.createBindings (/Users/matijaabicic/.atom/packages/minimap-git-diff/lib/minimap-git-diff.coffee:56:20)
  at MinimapGitDiff.createBindings (/Users/matijaabicic/.atom/packages/minimap-git-diff/lib/minimap-git-diff.coffee:1:1)
  at /Users/matijaabicic/.atom/packages/minimap-git-diff/lib/minimap-git-diff.coffee:51:10
  at Project.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at Project.module.exports.Project.setPaths (/Applications/Atom.app/Contents/Resources/app/src/project.js:210:12)
  at Ipc.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:38:25)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)

```

### Commands

```
     -0:00.0 pane:reopen-closed-item (input.hidden-input)
```

### Config

```
{}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v0.21.0
color-picker, v1.2.5
jshint, v1.1.0
minimap, v3.3.3
minimap-color-highlight, v3.0.1
minimap-find-and-replace, v3.0.0
minimap-git-diff, v3.0.4
minimap-highlight-selected, v3.0.0
minimap-selection, v3.0.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by abe33** [comment]
Please see #6, it's mostly a version issue with the package, updates haven't been notified to users since 3.0.5 due to the change of repo in `package.json`.
